version: 2.1
jobs:
  guidion-testing:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - testing:
          FILELOCATION: check/test.py
    #   - checkout
    #   - run:
    #       command: python3 -m pip install -r requirements.txt
    #   - run:
    #       command: python3 test.py
workflows:
  publish:
    jobs:
      - guidion-testing:
          # context: guidion-bi-serverless
        filters:
          branches:
            only:
              - master
commands:
  testing:
    parameters:
      FILELOCATION:
        type: string
    description: "Python unittest job"
    steps:
      - checkout
      - run:
          command: python3 -m pip install -r requirements.txt
      - run:
          command: python3 << parameters.FILELOCATION >>
