version: 2.1
jobs:
  guidion-testing:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - run:
        command: python3 -m pip install -r requirements.txt
workflows:
  publish:
    jobs:
      - guidion-testing:
          # context: guidion-bi-serverless
        filters:
          branches:
            only:
              - master
# commands:
#   testing:
#     description: "Python unittest job"
#     steps:
#       - checkout
#       - run:
