version: 2.1
jobs:
  guidion-testing:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - hold:
          type: approval
      - testing:
          FILELOCATION: test.py
          requires:
            - hold
workflows:
  publish:
    jobs:
      - guidion-testing:
          # context: guidion-bi-serverless
        filters:
          branches:
            only:
              - develop
commands:
  testing:
    parameters:
      FILELOCATION:
        type: string
    description: "Python unittest job"
    steps:
      - checkout
      - run:
          name: Install test job dependencies
          command: python3 -m pip install -r requirements.txt
      - run:
          name: Make it executable
          command: chmod +x .circleci/run_unittests.sh
      - run:
          name: Run the file
          command: .circleci/run_unittests.sh
